# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:

  - os: linux
    env:
      - PYTHON_VER='3.6'

  #- os: linux
  #  env:
  #    - PYTHON_VER='2.7'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

# Build out environment
  #- conda create -n tenv python=$PYTHON_VER cmake numpy ci-psi4 psi4 -c psi4/label/dev -c psi4
  - conda create -n tenv python=$PYTHON_VER cmake numpy nomkl
  - source activate tenv
  - conda install pytest pytest-cov codecov deepdiff -c conda-forge
  - conda list

before_script:
  - python -V
  - cd ${TRAVIS_BUILD_DIR}
  - > 
      cmake -Bbuild -H. 
      -DCMAKE_BUILD_TYPE=Release
      -DPYTHON_EXECUTABLE="${HOME}/miniconda/envs/tenv/bin/python"
      -DCMAKE_INSTALL_PREFIX=${HOME}/{{ cookiecutter.project_slug }}-install
  - cd build
  - make -j2
  - make install

script:
  - cd ${HOME}/{{ cookiecutter.project_slug }}-install && PYTHONPATH=lib/ python -m pytest -rws -v --capture=sys --cov

notifications:
    email: false

after_success:
  - codecov

